#pragma once

// Pure Find My / OpenHaystack advertisement construction: no FreeRTOS, no
// filesystem, no BLE. Header-only so host-side unit tests can exercise the
// exact byte layout (see doc/BeaconService.md and BeaconRulesTest.cpp).
//
// Input is a 28-byte advertisement key = the X-coordinate of a P-224 public
// key (big-endian, as generated by the companion).

#include <cstdint>
#include <cstring>

namespace Pinetime {
  namespace Controllers {
    namespace BeaconRules {
      static constexpr uint8_t KeySize = 28;

      // 6-byte value for NimBLE's ble_hs_id_set_rnd, in host byte order
      // (little-endian: out[0] is the LSB). The over-the-air address is
      // MSB..LSB = (advKey[0]|0xC0), advKey[1], advKey[2], advKey[3],
      // advKey[4], advKey[5]; the |0xC0 makes it a static random address.
      // The mapping is reversed relative to the big-endian ESP32 reference.
      inline void BuildAddress(const uint8_t advKey[KeySize], uint8_t out[6]) {
        out[0] = advKey[5];
        out[1] = advKey[4];
        out[2] = advKey[3];
        out[3] = advKey[2];
        out[4] = advKey[1];
        out[5] = static_cast<uint8_t>(advKey[0] | 0xC0);
      }

      // Raw 31-byte advertising data for ble_gap_adv_set_data.
      inline void BuildPayload(const uint8_t advKey[KeySize], uint8_t out[31]) {
        out[0] = 0x1e; // AD length 30
        out[1] = 0xff; // Manufacturer Specific Data
        out[2] = 0x4c; // Apple company id 0x004C, little-endian
        out[3] = 0x00;
        out[4] = 0x12; // Apple offline finding type
        out[5] = 0x19; // length 25
        out[6] = 0x00; // status
        std::memcpy(&out[7], &advKey[6], 22);
        out[29] = static_cast<uint8_t>(advKey[0] >> 6);
        out[30] = 0x00; // hint
      }
    }
  }
}
